---
abstract: 'async Pg with AnyEvent and Promises'
author:
  - 'Ruslan U. Zakirov <Ruslan.Zakirov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Poggy
name: DBIx-Poggy
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  DBD::Pg: 0
  DBI: 0
  Guard: 0
  Promises: 0
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
